[project]
name = "vbe"
version = "0.1.0"
description = ""
authors = [
    {name = "antoniibelyshev",email = "antoniy.belishev@gmail.com"}
]
readme = "README.md"
packages = [
    { include = "vbe" },
]
requires-python = ">=3.10"
dependencies = [
    "torch (>=2.5.1,<3.0.0)",
    "wandb (>=0.19.2,<0.20.0)",
    "torch-geometric (>=2.6.1,<3.0.0)",
    "netrd (>=0.3.0,<0.4.0)",
    "torchvision (>=0.20.1,<0.21.0)",
    "numpy (>=2.2.1,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
